### PR TITLE
Implements generic play json codec enumeration derivation, removes unneeded jackson-databind

### PR DESCRIPTION
**Pull request by fr3akX**

### CODE REVIEW

**Comment by t3hnar** [comment]
Could you please split the project on two modules, to narrow the scope of shapeless dependencies ?

**Comment by fr3akX** [comment]
sure, will do

**Comment by t3hnar** [comment]
I can merge this in, however it would be very handy to use `OWrites` and `OFormat`

**Comment by t3hnar** [comment]
@fr3akX indeed, I missed that you just return plain string..

**Pull request merged**
