### PR TITLE
Faster parsing and serialization of non-null values

### PR DESCRIPTION
**Pull request by plokhotnyuk**
Also:
- Add Scala 3 support for play-json-jsoniter
- Update Scala 2.x to 2.12.17 and 2.13.8
- Update Scala.js to 1.10.1
- Update play-json to 2.10.0-RC6
- Update jsoniter-scala-core to 2.17.3
- Update scala-collection-compact to 2.8.1
- Update shapeless to 2.3.10
- Update sbt plugin and CI dependencies

### CODE REVIEW

**Comment by t3hnar** [comment]
still draft? :)

**Comment by t3hnar** [comment]
@plokhotnyuk thanks for PR, could you please take a look into failing build?

**Comment by plokhotnyuk** [comment]
@t3hnar It looks like a network issue on CI nodes... Please restart actions and If no objections, merge and cut a release

**Comment by plokhotnyuk** [comment]
@t3hnar Finally I fixed all CI issues after upgrading of all kinds of dependencies.

Please consider merging and cutting a release.

**Comment by t3hnar** [comment]
Thanks!

**Comment by t3hnar** [comment]
FYI: https://github.com/playframework/play-json/issues/798

**Pull request merged**
